### ISSUE TITLE
Remove the "compile" directory

### ISSUE THREAD

**Issue by amyboyd** [partnermarketing/pm-image-editor#2]
Source code control is for _source_ code, not _distributable_ code.

**Comment by BernardoSilva** [comment]
Having a `dist` or `compile` directory is very useful if we managed to put this library in a cdn. :)

**Comment by amyboyd** [comment]
@BernardoSilva That's what NPM is for. When you publish to NPM, you can include compiled files (not in Git) and exclude source files (kept in Git). That's done using .npmignore. E.g. see [this library](https://github.com/CityPantry/citypantry-js-lib/) - in Git there's no compiled files, but on NPM there are no source files and only compiled files. Source code control isn't for compiled code.

**Comment by osavchenko** [comment]
+1

**Comment by amyboyd** [comment]
Done in https://github.com/partnermarketing/pm-image-editor/commit/3b70e3ea7ff144e6a02d0e291c9847f118048245
